# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

"""Speculative decoding utilities."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

import numpy as np
import numpy.typing as npt
from max.driver import Buffer
from max.interfaces import GenerationStatus, RequestID, TextGenerationOutput
from max.pipelines.core import TextContext
from max.pipelines.lib.utils import upper_bounded_default

from ..pipeline_variants.text_generation import calculate_num_steps

logger = logging.getLogger("max.pipelines")


@runtime_checkable
class ModelInputsWithTokensAndOffsets(Protocol):
    """Protocol for model inputs with tokens and offsets."""

    tokens: Buffer
    input_row_offsets: Buffer


@dataclass
class SpeculativeDecodingMetrics:
    """Metrics for speculative decoding."""

    bonus_tokens_used: int
    draft_tokens_accepted: int
    draft_tokens_generated: int
    total_acceptance_lengths: int
    num_generations: int

    @classmethod
    def empty(self) -> SpeculativeDecodingMetrics:
        """Create an empty metrics object."""
        return SpeculativeDecodingMetrics(
            bonus_tokens_used=0,
            draft_tokens_accepted=0,
            draft_tokens_generated=0,
            total_acceptance_lengths=0,
            num_generations=0,
        )

    def update(
        self,
        new_metrics: SpeculativeDecodingMetrics,
    ) -> None:
        """Update metrics with results from a batch.

        Args:
            new_metrics: The new metrics to update with
        """
        self.draft_tokens_generated += new_metrics.draft_tokens_generated
        self.draft_tokens_accepted += new_metrics.draft_tokens_accepted
        self.bonus_tokens_used += new_metrics.bonus_tokens_used
        self.total_acceptance_lengths += new_metrics.total_acceptance_lengths
        self.num_generations += new_metrics.num_generations

    @property
    def acceptance_rate(self) -> float:
        """Get the acceptance rate."""
        if self.draft_tokens_generated == 0:
            return 0.0
        return self.draft_tokens_accepted / self.draft_tokens_generated

    @property
    def avg_acceptance_length(self) -> float:
        """Get the average acceptance length."""
        if self.num_generations == 0:
            return 0.0
        return self.total_acceptance_lengths / self.num_generations

    def __str__(self) -> str:
        """String representation of current metrics."""
        return (
            f"SpeculativeDecodingMetrics("
            f"acceptance_rate={self.acceptance_rate:.2%}, "
            f"avg_acceptance_length={self.avg_acceptance_length:.2f}, "
            f"bonus_tokens_used={self.bonus_tokens_used}, "
            f"draft_tokens_accepted={self.draft_tokens_accepted}/{self.draft_tokens_generated})"
        )


# TODO: dedup update_contexts_and_compute_metrics_standalone and update_contexts_and_compute_metrics_eagle!
# there are minor differences that are very non-obvious.
def update_contexts_and_compute_metrics_standalone(
    context_batch: list[TextContext],
    first_rejected_tokens: npt.NDArray[np.integer[Any]],
    recovered_tokens: npt.NDArray[np.integer[Any]],
    bonus_tokens: npt.NDArray[np.integer[Any]] | None,
    draft_tokens: npt.NDArray[np.integer[Any]],
    num_draft_tokens_generated: int,
) -> SpeculativeDecodingMetrics:
    """Update contexts with the results of token generation.

    Args:
        context_batch: The list of context objects
        first_rejected_tokens: Array indicating the indices of first rejected tokens
        recovered_tokens: Array of recovered tokens from target model
        bonus_tokens: Array of bonus tokens from target model
        draft_tokens: Array of draft tokens
        num_draft_tokens_generated: Number of tokens generated by the draft model
    """
    total_draft_accepted = 0
    total_bonus_used = 0
    acceptance_lengths = []

    for idx, rejected_token_idx in enumerate(first_rejected_tokens):
        context = context_batch[idx]
        rejected_token_idx = rejected_token_idx.item()

        for token_idx in range(rejected_token_idx):
            token = int(draft_tokens[idx, token_idx])
            context.update(token)

        if (
            rejected_token_idx == num_draft_tokens_generated
            and bonus_tokens is not None
        ):
            context.update(bonus_tokens[idx, 0].item())
            total_bonus_used += 1
        else:
            # For residual sampler, index by rejected position;
            # for greedy sampler (or no bonus), always index 0.
            recover_idx = rejected_token_idx if bonus_tokens is not None else 0
            context.update(recovered_tokens[idx, recover_idx].item())

        total_draft_accepted += rejected_token_idx
        acceptance_lengths.append(rejected_token_idx)

        # When some or all draft tokens are rejected, we apply a token from
        # the residual distribution. The draft and target models have not
        # processed this token so the context goes back one step for both
        # of the models to process that token.
        # If all draft tokens are accepted, then the draft model has not
        # processed the bonus token. In this case only the draft needs to
        # go one step back. At the moment we do this for all cases.
        context.tokens.rewind_processing(1)

    total_draft_generated = num_draft_tokens_generated * len(context_batch)
    return SpeculativeDecodingMetrics(
        bonus_tokens_used=total_bonus_used,
        draft_tokens_accepted=total_draft_accepted,
        draft_tokens_generated=total_draft_generated,
        total_acceptance_lengths=sum(acceptance_lengths),
        num_generations=1,
    )


def update_contexts_and_compute_metrics_eagle(
    context_batch: list[TextContext],
    first_rejected_tokens: npt.NDArray[np.integer[Any]],
    recovered_tokens: npt.NDArray[np.integer[Any]],
    bonus_tokens: npt.NDArray[np.integer[Any]] | None,
    draft_tokens: npt.NDArray[np.integer[Any]],
    num_draft_tokens_generated: int,
) -> SpeculativeDecodingMetrics:
    """Update contexts after EAGLE verification.

    EAGLE-specific behavior:
    - Target token was already added via jump_ahead (start_idx not updated)
    - Draft indices were bumped for KV cache but tokens not written
    - After verification, we "commit" the target token and write accepted draft tokens
    """
    total_draft_generated = num_draft_tokens_generated * len(context_batch)
    total_draft_accepted = 0
    total_bonus_used = 0
    acceptance_lengths = []

    for idx, context in enumerate(context_batch):
        rejected_token_idx = int(first_rejected_tokens[idx].item())

        for token_idx in range(rejected_token_idx):
            if context.is_done:
                break
            token = int(draft_tokens[idx, token_idx])
            context.update(token)

        if not context.is_done:
            if rejected_token_idx < num_draft_tokens_generated:
                # Draft token rejected - use recovered token from target
                # Greedy sampler: recovered_tokens shape is [batch_size, 1]
                # Residuals sampler: recovered_tokens shape is [batch_size, num_steps]
                if bonus_tokens is None:
                    # Greedy sampler - only one recovered token per batch
                    token = int(recovered_tokens[idx, 0])
                else:
                    # Residual sampler - tokens for all positions
                    token = int(recovered_tokens[idx, rejected_token_idx])
                context.update(token)
            elif bonus_tokens is not None:
                # All drafts accepted + bonus token available
                token = int(bonus_tokens[idx, 0])
                total_bonus_used += 1
                context.update(token)

        # This is added because the draft needs to process the same tokens but
        # with the hidden states received from the target model.
        # This will also set the start index to the correct position for the kv cache
        context.apply_processing_offset(-rejected_token_idx)

        # Cap draft_kv_start_idx to processed_length so stale draft KV
        # entries (from rejected tokens) get overwritten on the next
        # iteration.
        state = context.spec_decoding_state
        state.draft_kv_start_idx = min(
            state.draft_kv_start_idx,
            context.tokens.processed_length,
        )

        total_draft_accepted += rejected_token_idx
        acceptance_lengths.append(rejected_token_idx)

    return SpeculativeDecodingMetrics(
        bonus_tokens_used=total_bonus_used,
        draft_tokens_accepted=total_draft_accepted,
        draft_tokens_generated=total_draft_generated,
        total_acceptance_lengths=sum(acceptance_lengths),
        num_generations=1,
    )


def build_response(
    context_batch: list[TextContext], max_seq_len: int
) -> dict[RequestID, TextGenerationOutput]:
    """Build response from updated contexts.

    Args:
        context_batch: The list of context objects
        max_seq_len: The maximum sequence length

    Returns:
        Dictionary mapping request IDs to TextGenerationOutput objects
    """
    res: dict[RequestID, TextGenerationOutput] = {}

    for context in context_batch:
        # Identify the Max Length
        context_max_length = upper_bounded_default(
            upper_bound=max_seq_len, default=context.max_length
        )

        # Break early if beyond max length
        current_length = context.tokens.processed_length + 1
        if current_length >= context_max_length:
            context.status = GenerationStatus.MAXIMUM_LENGTH

        output = context.to_generation_output()
        if output.tokens:
            res[context.request_id] = output

    return res


def compute_max_num_draft_steps(
    replica_batches: list[list[TextContext]],
    desired_num_draft_steps: int,
    max_seq_len: int,
    is_draft: bool,
) -> int:
    """Compute the maximum number of draft steps that can be run for a batch."""
    max_seq_len = max_seq_len - 1 if is_draft else max_seq_len
    num_draft_steps = desired_num_draft_steps
    for replica_batch in replica_batches:
        for context in replica_batch:
            num_draft_steps = calculate_num_steps(
                context, num_draft_steps, max_seq_len
            )
    return num_draft_steps


def seek_processing_position(
    context: TextContext,
    target_position: int,
) -> None:
    """Seek the processing position to the target position."""
    delta = target_position - context.tokens.processed_length
    if delta > 0:
        context.tokens.skip_processing(delta)
    elif delta < 0:
        context.tokens.rewind_processing(-delta)


def shift_draft_tokens(
    tokens: npt.NDArray[np.integer[Any]],
    batch: list[TextContext],
    shift_next_tokens: npt.NDArray[np.int64],
) -> npt.NDArray[np.integer[Any]]:
    """Shift each context's tokens left by 1, appending the given token.

    For chunked prefill, the draft model needs to see the same prompt
    tokens but with positions shifted so the last token in each
    context's span is replaced by the target-sampled next token.
    """
    shifted = np.empty_like(tokens)
    offset = 0
    for i, ctx in enumerate(batch):
        n = ctx.tokens.active_length
        shifted[offset : offset + n - 1] = tokens[offset + 1 : offset + n]
        shifted[offset + n - 1] = shift_next_tokens[i]
        offset += n
    return shifted
