# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

"""Speculative decoding utilities."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

import numpy as np
import numpy.typing as npt
from max.driver import Buffer
from max.interfaces import GenerationStatus, RequestID, TextGenerationOutput
from max.pipelines.core import TextContext
from max.pipelines.lib.utils import upper_bounded_default

from ..pipeline_variants.text_generation import calculate_num_steps

logger = logging.getLogger("max.pipelines")


@runtime_checkable
class ModelInputsWithTokensAndOffsets(Protocol):
    """Protocol for model inputs with tokens and offsets."""

    tokens: Buffer
    input_row_offsets: Buffer


@dataclass
class SpeculativeDecodingMetrics:
    """Metrics for speculative decoding."""

    num_speculative_tokens: int
    """The number of draft tokens the pipeline will speculate each time."""

    draft_tokens_accepted: int
    """The number of draft tokens accepted by the target model."""

    draft_tokens_generated: int
    """The number of draft tokens generated by the draft model.

    This must be a multiple of num_speculative_tokens and be at least as large
    as draft_tokens_accepted.
    """

    def __post_init__(self) -> None:
        if self.draft_tokens_generated % self.num_speculative_tokens != 0:
            raise ValueError(
                "draft_tokens_generated must be a multiple of num_speculative_tokens"
            )
        if self.draft_tokens_accepted > self.draft_tokens_generated:
            raise ValueError(
                "draft_tokens_accepted must be less than or equal to draft_tokens_generated"
            )

    @classmethod
    def empty(self, num_speculative_tokens: int) -> SpeculativeDecodingMetrics:
        """Create an empty metrics object."""
        return SpeculativeDecodingMetrics(
            num_speculative_tokens=num_speculative_tokens,
            draft_tokens_accepted=0,
            draft_tokens_generated=0,
        )

    def update(
        self,
        draft_tokens_accepted: int,
        draft_tokens_generated: int,
    ) -> None:
        """Update metrics with results from a batch."""
        assert draft_tokens_generated % self.num_speculative_tokens == 0
        assert draft_tokens_accepted <= draft_tokens_generated
        self.draft_tokens_accepted += draft_tokens_accepted
        self.draft_tokens_generated += draft_tokens_generated

    @property
    def acceptance_rate(self) -> float:
        """Get the acceptance rate."""
        if self.draft_tokens_generated == 0:
            return 0.0
        return self.draft_tokens_accepted / self.draft_tokens_generated

    @property
    def avg_acceptance_length(self) -> float:
        """Get the average acceptance length."""
        if self.draft_tokens_generated == 0:
            return 0.0
        num_generations = (
            self.draft_tokens_generated // self.num_speculative_tokens
        )
        if num_generations == 0:
            return 0.0
        return self.draft_tokens_accepted / num_generations


# TODO: delete this method!
def update_contexts_and_compute_metrics_standalone(
    context_batch: list[TextContext],
    first_rejected_tokens: npt.NDArray[np.integer[Any]],
    recovered_tokens: npt.NDArray[np.integer[Any]],
    bonus_tokens: npt.NDArray[np.integer[Any]] | None,
    draft_tokens: npt.NDArray[np.integer[Any]],
    num_draft_tokens_generated: int,
) -> tuple[int, int]:
    """Update contexts with the results of token generation.

    Args:
        context_batch: The list of context objects
        first_rejected_tokens: Array indicating the indices of first rejected tokens
        recovered_tokens: Array of recovered tokens from target model
        bonus_tokens: Array of bonus tokens from target model
        draft_tokens: Array of draft tokens
        num_draft_tokens_generated: Number of tokens generated by the draft model
    """
    total_draft_accepted = 0
    acceptance_lengths = []

    for idx, rejected_token_idx in enumerate(first_rejected_tokens):
        context = context_batch[idx]
        rejected_token_idx = rejected_token_idx.item()

        for token_idx in range(rejected_token_idx):
            token = int(draft_tokens[idx, token_idx])
            context.update(token)

        if (
            rejected_token_idx == num_draft_tokens_generated
            and bonus_tokens is not None
        ):
            context.update(bonus_tokens[idx, 0].item())
        else:
            # For residual sampler, index by rejected position;
            # for greedy sampler (or no bonus), always index 0.
            recover_idx = rejected_token_idx if bonus_tokens is not None else 0
            context.update(recovered_tokens[idx, recover_idx].item())

        total_draft_accepted += rejected_token_idx
        acceptance_lengths.append(rejected_token_idx)

        # When some or all draft tokens are rejected, we apply a token from
        # the residual distribution. The draft and target models have not
        # processed this token so the context goes back one step for both
        # of the models to process that token.
        # If all draft tokens are accepted, then the draft model has not
        # processed the bonus token. In this case only the draft needs to
        # go one step back. At the moment we do this for all cases.
        context.tokens.rewind_processing(1)

    total_draft_generated = num_draft_tokens_generated * len(context_batch)
    return total_draft_accepted, total_draft_generated


def build_response(
    context_batch: list[TextContext], max_seq_len: int
) -> dict[RequestID, TextGenerationOutput]:
    """Build response from updated contexts.

    Args:
        context_batch: The list of context objects
        max_seq_len: The maximum sequence length

    Returns:
        Dictionary mapping request IDs to TextGenerationOutput objects
    """
    res: dict[RequestID, TextGenerationOutput] = {}

    for context in context_batch:
        # Identify the Max Length
        context_max_length = upper_bounded_default(
            upper_bound=max_seq_len, default=context.max_length
        )

        # Break early if beyond max length
        current_length = context.tokens.processed_length + 1
        if current_length >= context_max_length:
            context.status = GenerationStatus.MAXIMUM_LENGTH

        output = context.to_generation_output()
        if output.tokens:
            res[context.request_id] = output

    return res


def compute_max_num_draft_steps(
    replica_batches: list[list[TextContext]],
    desired_num_draft_steps: int,
    max_seq_len: int,
    is_draft: bool,
) -> int:
    """Compute the maximum number of draft steps that can be run for a batch."""
    max_seq_len = max_seq_len - 1 if is_draft else max_seq_len
    num_draft_steps = desired_num_draft_steps
    for replica_batch in replica_batches:
        for context in replica_batch:
            num_draft_steps = calculate_num_steps(
                context, num_draft_steps, max_seq_len
            )
    return num_draft_steps
