# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

"""Importable stub for the ``m`` dialect.

MLIR's ``loadDialectModule`` searches ``max._mlir.dialects.<dialect>``
before every type-caster lookup and only caches *successful* imports —
``ModuleNotFoundError`` is re-attempted on every call. This dialect
doesn't ship autogenerated tablegen Python output (only ``mo`` and
``rmo`` do), so without this stub every ``Attribute.parse`` /
``Type.parse`` for an ``m`` entity (e.g. ``DeviceRefAttr``) repeats a
full ``PyImport_ImportModule`` failure.

Type bindings live in ``max._core.dialects.m`` (registered via
nanobind). This stub exists purely so the import succeeds and populates
the ``loadedDialectModules`` cache. Replace with a real generated file
if ``m`` ever ships proper Python op bindings.
"""
